/**
 * Generate pre-rendered setup screen bitmap for ESP32
 *
 * Run from server directory: node ../Arduino/epcal/generate_qr.js
 * (to use existing canvas/qrcode dependencies)
 *
 * Output: src/setup_screen.h
 */

const { createCanvas, loadImage } = require('canvas');
const QRCode = require('qrcode');
const fs = require('fs');
const path = require('path');

const WIFI_SSID = "EPCAL-Setup";
const CONFIG_URL = "http://192.168.4.1";

// Display chunk dimensions (top half in landscape)
const CHUNK_WIDTH = 1304;
const CHUNK_HEIGHT = 492;

async function generateSetupScreen() {
  console.log('Generating setup screen bitmap...');
  console.log(`Size: ${CHUNK_WIDTH}x${CHUNK_HEIGHT}`);

  // Create canvas
  const canvas = createCanvas(CHUNK_WIDTH, CHUNK_HEIGHT);
  const ctx = canvas.getContext('2d');

  // Fill with white background
  ctx.fillStyle = 'white';
  ctx.fillRect(0, 0, CHUNK_WIDTH, CHUNK_HEIGHT);

  // Draw title
  ctx.fillStyle = 'black';
  ctx.font = 'bold 36px sans-serif';
  ctx.fillText('CONFIGURATION EPCAL', 50, 50);

  ctx.font = '24px sans-serif';
  ctx.fillText('Scannez les codes QR pour configurer', 50, 90);

  // Generate QR codes
  const wifiText = `WIFI:T:nopass;S:${WIFI_SSID};;`;

  // QR code positions - centered better
  const qr1X = 150;
  const qr2X = 700;
  const qrY = 130;
  const qrSize = 220;

  // Draw WiFi QR code
  const wifiQRDataUrl = await QRCode.toDataURL(wifiText, {
    width: qrSize,
    margin: 1,
    errorCorrectionLevel: 'L'
  });

  // Draw URL QR code
  const urlQRDataUrl = await QRCode.toDataURL(CONFIG_URL, {
    width: qrSize,
    margin: 1,
    errorCorrectionLevel: 'L'
  });

  // Load and draw QR images
  const wifiQRImage = await loadImage(wifiQRDataUrl);
  ctx.drawImage(wifiQRImage, qr1X, qrY, qrSize, qrSize);

  const urlQRImage = await loadImage(urlQRDataUrl);
  ctx.drawImage(urlQRImage, qr2X, qrY, qrSize, qrSize);

  // Labels under QR codes
  ctx.font = 'bold 28px sans-serif';
  const labelY = qrY + qrSize + 35;
  ctx.fillText('1. WiFi', qr1X + 60, labelY);
  ctx.fillText('2. Configuration', qr2X + 20, labelY);

  ctx.font = '22px sans-serif';
  ctx.fillText(WIFI_SSID, qr1X + 40, labelY + 35);
  ctx.fillText(CONFIG_URL, qr2X, labelY + 35);

  // Convert to 1-bit bitmap
  // E-paper format: 1 = white, 0 = black, MSB first
  const imageData = ctx.getImageData(0, 0, CHUNK_WIDTH, CHUNK_HEIGHT);
  const pixels = imageData.data;

  const bytesPerRow = Math.ceil(CHUNK_WIDTH / 8);
  const totalBytes = bytesPerRow * CHUNK_HEIGHT;
  const bitmap = new Uint8Array(totalBytes);

  // Initialize all to white (0xFF)
  bitmap.fill(0xFF);

  for (let y = 0; y < CHUNK_HEIGHT; y++) {
    for (let x = 0; x < CHUNK_WIDTH; x++) {
      const pixelIndex = (y * CHUNK_WIDTH + x) * 4;
      const r = pixels[pixelIndex];
      const g = pixels[pixelIndex + 1];
      const b = pixels[pixelIndex + 2];

      // Convert to grayscale and threshold
      const gray = (r + g + b) / 3;
      const isBlack = gray < 128;

      if (isBlack) {
        // Clear bit for black pixel
        const byteIndex = y * bytesPerRow + Math.floor(x / 8);
        const bitIndex = 7 - (x % 8);
        bitmap[byteIndex] &= ~(1 << bitIndex);
      }
    }
  }

  console.log(`Generated ${totalBytes} bytes (${bytesPerRow} bytes per row)`);

  // Generate C header file
  let header = `/**
 * Pre-rendered setup screen bitmap (top half only)
 *
 * Generated by generate_qr.js
 * DO NOT EDIT MANUALLY
 *
 * Contains: Title, WiFi QR code, Config URL QR code, labels
 * Size: ${CHUNK_WIDTH}x${CHUNK_HEIGHT} pixels = ${totalBytes} bytes
 * Format: 1-bit, MSB first, 1=white, 0=black
 */

#ifndef SETUP_SCREEN_H
#define SETUP_SCREEN_H

#include <Arduino.h>

#define SETUP_SCREEN_WIDTH ${CHUNK_WIDTH}
#define SETUP_SCREEN_HEIGHT ${CHUNK_HEIGHT}
#define SETUP_SCREEN_BYTES ${totalBytes}

static const uint8_t setup_screen_bitmap[] PROGMEM = {
`;

  // Format as C array (16 bytes per line)
  for (let i = 0; i < totalBytes; i++) {
    if (i % 16 === 0) header += '  ';
    header += `0x${bitmap[i].toString(16).padStart(2, '0')}`;
    if (i < totalBytes - 1) header += ', ';
    if (i % 16 === 15 || i === totalBytes - 1) header += '\n';
  }

  header += `};

#endif // SETUP_SCREEN_H
`;

  // Determine output path (same directory as this script, in src/)
  const scriptDir = __dirname;
  const outputPath = path.join(scriptDir, 'src', 'setup_screen.h');
  fs.writeFileSync(outputPath, header);
  console.log(`Generated ${outputPath}`);

  // Also save a PNG preview
  const previewPath = path.join(scriptDir, 'setup_screen_preview.png');
  const out = fs.createWriteStream(previewPath);
  const stream = canvas.createPNGStream();
  stream.pipe(out);
  out.on('finish', () => console.log(`Generated ${previewPath}`));
}

generateSetupScreen().catch(console.error);
