# Build configuration for Home Assistant Add-on
# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-advanced-options

build_from:
  amd64: node:20-slim
  aarch64: node:20-slim
  armv7: node:20-slim

args:
  BASHIO_VERSION: "0.16.2"
