"""Constants for E-Ink Calendar renderer - no Home Assistant dependencies."""

# MDI icon to Unicode symbol mapping for calendar icons
MDI_TO_UNICODE = {
    "mdi:calendar": "●",
    "mdi:briefcase": "■",
    "mdi:home": "▲",
    "mdi:school": "◆",
    "mdi:heart": "♥",
    "mdi:star": "★",
    "mdi:flag": "⚑",
    "mdi:trophy": "🏆",
    "mdi:cake": "🎂",
    "mdi:gift": "🎁",
    "mdi:phone": "☎",
    "mdi:email": "✉",
    "mdi:car": "🚗",
    "mdi:airplane": "✈",
    "mdi:train": "🚂",
    "mdi:walk": "🚶",
    "mdi:run": "🏃",
    "mdi:bike": "🚲",
    "mdi:umbrella": "☂",
    "mdi:sun": "☀",
    "mdi:moon": "🌙",
    "mdi:music": "♪",
    "mdi:movie": "🎬",
    "mdi:book": "📖",
    "mdi:pencil": "✏",
    "mdi:trash-can": "🗑️",
    "mdi:recycle": "♻",
    "mdi:leaf": "🍃",
    "mdi:tree": "🌳",
    "mdi:flower": "🌸",
    "mdi:paw": "🐾",
    "mdi:food": "🍴",
    "mdi:coffee": "☕",
    "mdi:pizza": "🍕",
    "mdi:glass-wine": "🍷",
}
